# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puesto_votacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVotanteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesa', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(db_column='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('puesto', models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.CASCADE, to='puesto_votacion.puestovotacionmodel')),
            ],
            options={
                'verbose_name': 'registro votante',
                'verbose_name_plural': 'registro votantes',
                'db_table': 'registro_votante',
                'managed': True,
            },
        ),
    ]
