# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_votante', '0001_initial'),
        ('votante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotantemodel',
            name='votante',
            field=models.OneToOneField(db_column='votante', on_delete=django.db.models.deletion.CASCADE, to='votante.votantemodel'),
        ),
    ]
