# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoUsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='soporte/')),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(db_column='active', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anexo usuario',
                'verbose_name_plural': 'Anexo usuarios',
                'db_table': 'anexo_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnexoVotanteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='soporte/')),
                ('comentario', models.CharField(max_length=100)),
                ('active', models.BooleanField(db_column='active', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anexo votante',
                'verbose_name_plural': 'Anexo votantes',
                'db_table': 'anexo_votante',
                'managed': True,
            },
        ),
    ]
