# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votante', '0001_initial'),
        ('anexo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexovotantemodel',
            name='votante',
            field=models.ForeignKey(db_column='votante', on_delete=django.db.models.deletion.CASCADE, to='votante.votantemodel'),
        ),
        migrations.AddField(
            model_name='anexousuariomodel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
