# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=255, null=True)),
                ('eslogan', models.CharField(blank=True, db_column='eslogan', max_length=255, null=True)),
                ('logo', models.FileField(blank=True, db_column='logo', null=True, upload_to='soporte/')),
                ('partido', models.CharField(blank=True, db_column='partido', max_length=255, null=True)),
                ('candidato', models.CharField(blank=True, db_column='candidato', max_length=255, null=True)),
                ('active', models.BooleanField(db_column='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campaña',
                'db_table': 'campana',
                'managed': True,
            },
        ),
    ]
