# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivipolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('referencia', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('comentario', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField(db_column='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(db_column='ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='config.ciudadmodel')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='config.departamentomodel')),
            ],
            options={
                'verbose_name': 'Divipol',
                'verbose_name_plural': 'Divipol',
                'db_table': 'divipol',
                'managed': True,
            },
        ),
    ]
