# Generated by Django 4.1.3 on 2022-11-02 21:10

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campana', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nodocumento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('movil', models.IntegerField(blank=True, db_column='movil', null=True)),
                ('fijo', models.IntegerField(blank=True, db_column='fijo', null=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=70)),
                ('firma', models.FileField(blank=True, null=True, upload_to='soporte/')),
                ('campana', models.ForeignKey(db_column='campana', on_delete=django.db.models.deletion.DO_NOTHING, to='campana.campanamodel')),
                ('ciudad', models.ForeignKey(db_column='ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='config.ciudadmodel')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='config.departamentomodel')),
                ('estado_usuario', models.ForeignKey(db_column='estado_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='config.estadousuariomodel')),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.DO_NOTHING, to='config.generomodel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tipo_documento', models.ForeignKey(db_column='tipo_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='config.tipodocumentomodel')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
