# Generated by Django 4.1.3 on 2022-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zona_votacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoVotacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=60)),
                ('mesa', models.IntegerField()),
                ('potencial', models.IntegerField()),
                ('active', models.BooleanField(db_column='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(db_column='zona', on_delete=django.db.models.deletion.CASCADE, to='zona_votacion.zonavotacionmodel')),
            ],
            options={
                'verbose_name': 'puesto votacion',
                'verbose_name_plural': 'puesto de votaciones',
                'db_table': 'puesto_votacion',
                'managed': True,
            },
        ),
    ]
